### PR TITLE
check that 2 is a tty.

### PR DESCRIPTION
**Pull request by jsg2021**
Attempting to construct a tty.WriteStream under electron crashes when launched detached from a tty

### CODE REVIEW

**Comment by 131** [comment]
I think nwjs & electron behave the here.
Could you re-use the `if(nw) (` check ( and probably rename it to a somewhat more generic if(nwORelectron) ) rather than rewrite everything with a tty.isatty to achieve electron support ?

**Comment by jsg2021** [comment]
Sure,
I was attempting to be specific about checking that stderr is 'is a tty' before using it, so I didn't bake in electron specific verbiage. I didn't know what `nw` was referring to so I left it as is.

**Comment by jsg2021** [comment]
the `nw` checks were insufficient. I've changed it to just check that `stderr` is set before `write`ing and `pipe`ing.

**Comment by 131** [comment]
Merged, waiting for CI to publish

**Comment by 131** [comment]
1.0.9 is available

**Comment by jsg2021** [comment]
thanks!

**Pull request merged**
